### ISSUE TITLE
Add a /predicates API call to return list of predicates used by the beacon and their definitions?

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATS-Tangerine/translator-knowledge-beacon#26]
It would actually be helpful in beacon client design to have access to the full list of predicates being used in statements from a beacon, plus a precise definition on their interpretation including directionality of application (e.g. subject => predicate => object direction).  At some point, one may even suggest that a global ontology of predicates be established with a central catalog of predicates established to encourage reuse (and perhaps, global CURIEs)

This proposed API call obviously should also be proxied and pooled through to the beacon-aggregator

**Comment by micheldumontier** [comment]
Indeed - I previously suggested that we return a list of predicates, and also a metamap comprised of subject type - predicate - object type statements.  take a look at statistics that we generate for bio2rdf's drugbank
http://download.bio2rdf.org/release/3/drugbank/drugbank.html

**Comment by RichardBruskiewich** [comment]
Point well taken. Hold that thought Michel... Chris and I talked about upgrading the Knowledge Beacon model to a richer (semantic web-like) model, so perhaps, we can incorporate this level of meta-data into the next major generation API.

**Comment by RichardBruskiewich** [comment]
The /predicates endpoint was implemented some time ago
